### ISSUE TITLE
Installed capacity chart split by technology

### ISSUE THREAD

**Issue by olafveerman** [climatescope/climatescope.org#161]
Current chart:

![image](https://cloud.githubusercontent.com/assets/751330/24003446/e49dc7ca-0a39-11e7-9ded-6169b72c523d.png)

Next steps:

- [x] provide data split by technology (@luizademoro)
- [x] prep data to include different technologies (@olafveerman)
- [x] tweak styling of the chart (@dylanmoriarty)

**Comment by olafveerman** [comment]
@DylanMoriarty Over to you.

A draft of the data is up on the following branch: https://github.com/climatescope/climatescope.org/tree/feature/161-chart-technology

As example: [argentina](https://raw.githubusercontent.com/climatescope/climatescope.org/12d820ccd54ab658b33c31ed733b35d99500f8dd/app/en/api/auxiliary/installed-capacity/ar.json)

With the big amount of categories, I'm wondering if the categories with 0 MW should be included in the graph.
For colors, would it be possible to use shades of yellow for the clean energy, and shades of grey for the non-clean?

**Comment by dtraum1** [comment]
Hi there,

I agree, the key and chart does not need to feature categories where the value is zero.
For the colors of the technologies, I would prefer something that differentiates more clearly the different technologies. For example: 
![image](https://cloud.githubusercontent.com/assets/17143506/25696878/ce8e15fa-30b0-11e7-96b2-204be80c85f9.png)

Thanks,
Dario

**Comment by DylanMoriarty** [comment]
It looks like there are a couple of issues with the data right now.

1. For each country, the Non-clean Energy field have no values.

```
    {
      "values": [],
      "name": "Non-clean Energy",
      "id": "non-clean-energy"
    },
```

2. For the all other fields, none of the values actually change over the given years.

```
    {
      "values": [
        {
          "global_average": null,
          "value": 2800.0,
          "year": 2010
        },
        {
          "global_average": null,
          "value": 2800.0,
          "year": 2011
        },
        {
          "global_average": null,
          "value": 2800.0,
          "year": 2012
      ...
      ],
      "name": "Large Hydro",
      "id": "large-hydro"
    },
```

Good news is once those things are fixed this won't take too long to implement. In the meantime I'll start putting together some colors for this & tweak the popup.

<img width="663" alt="screenshot 2017-05-04 18 27 53" src="https://cloud.githubusercontent.com/assets/9341928/25727579/eb2f8972-30f7-11e7-89d3-20331333c7a4.png">

**Comment by olafveerman** [comment]
@dylanmoriarty Ill fix the non changing values. Non clean will be removed as a category in itself
