### ISSUE TITLE
Regenerate new country maps

### ISSUE THREAD

**Issue by ricardomestre** [climatescope/climatescope.org#209]
Based on 2017 brand colors.

**Comment by olafveerman** [comment]
Check if it's easier to do this by implementing the map using Mapbox GL

**Comment by olafveerman** [comment]
@danielfdsilva Let's chat about what it would take to replace the statically generated images for Mapbox, or something along those lines.

**Comment by olafveerman** [comment]
New tilesets and styles generated and stored on Mapbox.

@danielfdsilva Did some first work to add Mapbox GL to the country pages. Code is up here: https://github.com/climatescope/climatescope.org/tree/feature/mb-map
We still need to hook up Angular to set correct bounds and the iso code. Over to you

**Comment by olafveerman** [comment]
This was fixed
