### ISSUE TITLE
Update results map background color

### ISSUE THREAD

**Issue by ricardomestre** [climatescope/climatescope.org#253]
Change results map background color to match wrapper's color:

![screen shot 2017-11-14 at 12 39 03](https://user-images.githubusercontent.com/1016701/32780425-088d73ce-c939-11e7-975f-d7ffea9d4413.png)

**Comment by olafveerman** [comment]
Done: https://github.com/developmentseed/climatescope-data/commit/13aa5574108028eb4fa6d1c2d7813416bc02912e
