### ISSUE TITLE
Restore state details and map

### ISSUE THREAD

**Issue by ricardomestre** [climatescope/climatescope.org#254]
Now:

![screen shot 2017-11-14 at 13 56 32](https://user-images.githubusercontent.com/1016701/32783483-d46591e8-c943-11e7-843c-f6aa4a21d6d5.png)

Versus:

![screen shot 2017-11-14 at 13 57 02](https://user-images.githubusercontent.com/1016701/32783491-d85406c2-c943-11e7-8a90-85de0d2a841d.png)

**Comment by danielfdsilva** [comment]
Data is not showing up because is not present in the api files

**Comment by olafveerman** [comment]
Data requested
