### ISSUE TITLE
Archive 2017

### ISSUE THREAD

**Issue by olafveerman** [climatescope/climatescope.org#296]
- [x] create 2017 repo - https://github.com/climatescope/climatescope-2017
- [x] change deploy key
- [x] change URL on the application side
- [x] set up new subdomain (requested)

cc @danielfdsilva

**Comment by olafveerman** [comment]
@danielfdsilva The build of the site is failing. Can you have a look at that?

**Comment by danielfdsilva** [comment]
This was done. Site live at http://2017.global-climatescope.org
