### ISSUE TITLE
Organize updates

### ISSUE THREAD

**Issue by olafveerman** [climatescope/climatescope.org#366]
Feedback

> Viewing updates: The "Updates" in the drop-down list gives users the potential to see very old (2017) content. Could we move what is currently in updates to "insights" and rename it to "Previous insights" and leave "updates" just for what we publish from now on?

**Comment by yunica** [comment]
This was implemented.
The redux function is updated to make the ` Previous Insights` filter at 2017.
To view update posts, you need to upload new posts (2018 or later).
