### ISSUE TITLE
Add 'developed markets' to ranking

### ISSUE THREAD

**Issue by olafveerman** [climatescope/climatescope.org#393]
Allow users to add ‘Developed markets’ to the ranking and compare their scores with the emerging markets.

Intended user flow:

* the [results page](https://global-climatescope.org/results) will load as-is. showing only emerging markets
* when the user clicks the button 'Add developed markets', the ranking is updated and developed countries are added

**Comment by yunica** [comment]
it was  implemented :rocket:.
