### ISSUE TITLE
Data Visualization Page

### ISSUE THREAD

**Issue by ricardomestre** [climatescope/climatescope.org#51]
Import/embed Data Visualization.

**Comment by olafveerman** [comment]
@ricardomestre data visualization accessible here: https://www.bnef.com/dataview/new-energy-outlook-2016/index.html

**Comment by olafveerman** [comment]
Additional comments:

> For the Executive summary page / dataviz let's use a page similar to that of the summaries, w/ opening paragraph, then big banner to the dataviz hosted outside, followed by full text and charts as we have done for the summaries (we will upload). The side bar menu on this page should link to all summaries (topic and regions) to make it a convenient place from which to navigate the site.

**Comment by olafveerman** [comment]
@ricardomestre Page scaffolded here: https://github.com/climatescope/climatescope.org/tree/feature/visualization

**Comment by olafveerman** [comment]
This is fixed in: https://github.com/climatescope/climatescope.org/pull/102
